name: Lint and Test

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  linter:
    strategy:
      fail-fast: true
      matrix:
        os: ["ubuntu-20.04"]
        python-version: ["3.6", "3.7", "3.8", "3.9", "3.10", "3.11"]
    defaults:
      run:
        shell: bash
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Set up Python v${{matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version}}
          cache: 'pip'
      - name: Install Dependencies
        run: python -m pip install -r requirements.txt
      - name: Run linter
        run: flake8

  test:
    strategy:
      fail-fast: true
      matrix:
        os: ["ubuntu-20.04"]
        python-version: ["3.6", "3.7", "3.8", "3.9", "3.10", "3.11"]
    defaults:
      run:
        shell: bash
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Set up Python v${{matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version}}
          cache: 'pip'
      - name: Install Dependencies
        run: python -m pip install -r requirements.txt
      - name: Run Tests
        run: pytest
