name: Publish to PyPI

on:
  push:
    tags:
      - '*.*.*'

permissions:
  contents: write
  id-token: write  # required for PyPI Trusted Publishing (OIDC)

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # fetch tags for changelog

      - name: Install uv and Python
        id: setup-uv
        uses: astral-sh/setup-uv@v5
        with:
          python-version: '3.12'
          enable-cache: true
          cache-dependency-glob: pyproject.toml

      - name: Install dev dependencies
        run: uv pip install -e .[dev]

      - name: Lint
        run: uv run ruff check .

      - name: Run tests
        run: uv run pytest -q

      - name: Build sdist and wheel
        run: uv build

      - name: Verify tag matches project version
        run: |
          TAG="${GITHUB_REF_NAME#v}"
          PY_VER=$(python -c "import tomllib;print(tomllib.load(open('pyproject.toml','rb'))['project']['version'])")
          echo "Tag: $TAG | Project version: $PY_VER"
          test "$TAG" = "$PY_VER"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          generate_release_notes: true

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist/
